using System.Drawing;
using System.Runtime.InteropServices;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Net.NetworkInformation;
using System.Security.Claims;
using System.Text.RegularExpressions;

namespace DataMatrix
{
    ///Just some data
    public class Data 
    {
        public List<string> FirstNameList { get; set; }
        public List<string> LastNameList { get; set; }

        public Data()
        {
            //I grabbed a list of the top 100 babynames for 2023.
            FirstNameList = new List<string>() {
                "Liam", "Olivia",
                "Noah", "Emma",
                "Oliver", "Charlotte",
                "James", "Amelia",
                "Elijah", "Sophia",
                "Mateo", "Mia",
                "Theodore", "Isabella",
                "Henry", "Ava",
                "Lucas", "Evelyn",
                "William", "Luna",
                "Benjamin", "Harper",
                "Levi", "Sofia",
                "Sebastian", "Camila",
                "Jack", "Eleanor",
                "Ezra", "Elizabeth",
                "Michael", "Violet",
                "Daniel", "Scarlett",
                "Leo", "Emily",
                "Owen", "Hazel",
                "Samuel", "Lily",
                "Hudson", "Gianna",
                "Alexander", "Aurora",
                "Asher", "Penelope",
                "Luca", "Aria",
                "Ethan", "Nora",
                "John", "Chloe",
                "David", "Ellie",
                "Jackson", "Mila",
                "Joseph", "Avery",
                "Mason", "Layla",
                "Luke", "Abigail",
                "Matthew", "Ella",
                "Julian", "Isla",
                "Dylan", "Eliana",
                "Elias", "Nova",
                "Jacob", "Madison",
                "Maverick", "Zoe",
                "Gabriel", "Ivy",
                "Logan", "Grace",
                "Aiden", "Lucy",
                "Thomas", "Willow",
                "Isaac", "Emilia",
                "Miles", "Riley",
                "Grayson", "Naomi",
                "Santiago", "Victoria",
                "Anthony", "Stella",
                "Wyatt", "Elena",
                "Carter", "Hannah",
                "Jayden", "Valentina",
                "Ezekiel", "Maya",
                "Caleb", "Zoey",
                "Cooper", "Delilah",
                "Josiah", "Leah",
                "Charles", "Lainey",
                "Christopher", "Lillian",
                "Isaiah", "Paisley",
                "Nolan", "Genesis",
                "Cameron", "Madelyn",
                "Nathan", "Sadie",
                "Joshua", "Sophie",
                "Kai", "Leilani",
                "Waylon", "Addison",
                "Angel", "Natalie",
                "Lincoln", "Josephine",
                "Andrew", "Alice",
                "Roman", "Ruby",
                "Adrian", "Claire",
                "Aaron", "Kinsley",
                "Wesley", "Everly",
                "Ian", "Emery",
                "Thiago", "Adeline",
                "Axel", "Kennedy",
                "Brooks", "Maeve",
                "Bennett", "Audrey",
                "Weston", "Autumn",
                "Rowan", "Athena",
                "Christian", "Eden",
                "Theo", "Iris",
                "Beau", "Anna",
                "Eli", "Eloise",
                "Silas", "Jade",
                "Jonathan", "Maria",
                "Ryan", "Caroline",
                "Leonardo", "Brooklyn",
                "Walker", "Quinn",
                "Jaxon", "Aaliyah",
                "Micah", "Vivian",
                "Everett", "Liliana",
                "Robert", "Gabriella",
                "Enzo", "Hailey",
                "Parker", "Sarah",
                "Jeremiah", "Savannah",
                "Jose", "Cora",
                "Colton", "Madeline",
                "Luka", "Natalia",
                "Easton", "Ariana",
                "Landon", "Lydia",
                "Jordan", "Lyla",
                "Amir", "Clara",
                "Gael", "Allison"
            };

            //I grabbed the last names from Wikipedia.
            LastNameList = new List<string>() {
                "Smith",
                "Johnson",
                "Williams",
                "Brown",
                "Jones",
                "Miller",
                "Davis",
                "Garcia",
                "Rodriguez",
                "Wilson",
                "Martinez",
                "Anderson",
                "Taylor",
                "Thomas",
                "Hernandez",
                "Moore",
                "Martin",
                "Jackson",
                "Thompson",
                "White",
                "Lopez",
                "Lee",
                "Gonzalez",
                "Harris",
                "Clark",
                "Lewis",
                "Robinson",
                "Walker",
                "Perez",
                "Hall",
                "Young",
                "Allen",
                "Sanchez",
                "Wright",
                "King",
                "Scott",
                "Green",
                "Baker",
                "Adams",
                "Nelson",
                "Hill",
                "Ramirez",
                "Campbell",
                "Mitchell",
                "Roberts",
                "Carter",
                "Phillips",
                "Evans",
                "Turner",
                "Torres",
                "Parker",
                "Collins",
                "Edwards",
                "Stewart",
                "Flores",
                "Morris",
                "Nguyen",
                "Murphy",
                "Rivera",
                "Cook",
                "Rogers",
                "Morgan",
                "Peterson",
                "Cooper",
                "Reed",
                "Bailey",
                "Bell",
                "Gomez",
                "Kelly",
                "Howard",
                "Ward",
                "Cox",
                "Diaz",
                "Richardson",
                "Wood",
                "Watson",
                "Brooks",
                "Bennett",
                "Gray",
                "James",
                "Reyes",
                "Cruz",
                "Hughes",
                "Price",
                "Myers",
                "Long",
                "Foster",
                "Sanders",
                "Ross",
                "Morales",
                "Powell",
                "Sullivan",
                "Russell",
                "Ortiz",
                "Jenkins",
                "Gutierrez",
                "Perry",
                "Butler",
                "Barnes",
                "Fisher"
            };
        }
    }
}